# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_syestates.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(758, 522)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(758, 522))
        MainWindow.setBaseSize(QtCore.QSize(758, 522))
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout_2.setHorizontalSpacing(1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.excel_but = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.excel_but.sizePolicy().hasHeightForWidth())
        self.excel_but.setSizePolicy(sizePolicy)
        self.excel_but.setMaximumSize(QtCore.QSize(80, 16777215))
        self.excel_but.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.excel_but.setObjectName("excel_but")
        self.gridLayout_2.addWidget(self.excel_but, 5, 4, 1, 1)
        self.comments_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comments_edit.sizePolicy().hasHeightForWidth())
        self.comments_edit.setSizePolicy(sizePolicy)
        self.comments_edit.setObjectName("comments_edit")
        self.gridLayout_2.addWidget(self.comments_edit, 5, 1, 1, 3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem)
        self.line = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_2.addItem(spacerItem1)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 6, 0, 1, 5)
        self.result_table = QtWidgets.QTableWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.result_table.setFont(font)
        self.result_table.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.result_table.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.result_table.setObjectName("result_table")
        self.result_table.setColumnCount(16)
        self.result_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.result_table.setHorizontalHeaderItem(15, item)
        self.result_table.horizontalHeader().setVisible(True)
        self.result_table.horizontalHeader().setCascadingSectionResizes(False)
        self.result_table.horizontalHeader().setMinimumSectionSize(32)
        self.gridLayout_2.addWidget(self.result_table, 8, 0, 1, 5)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 5, 0, 1, 1)
        self.neighborhood_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.neighborhood_edit.sizePolicy().hasHeightForWidth())
        self.neighborhood_edit.setSizePolicy(sizePolicy)
        self.neighborhood_edit.setMaximumSize(QtCore.QSize(180, 16777215))
        self.neighborhood_edit.setObjectName("neighborhood_edit")
        self.gridLayout_2.addWidget(self.neighborhood_edit, 2, 3, 1, 1)
        self.agent_combox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.agent_combox.sizePolicy().hasHeightForWidth())
        self.agent_combox.setSizePolicy(sizePolicy)
        self.agent_combox.setMaximumSize(QtCore.QSize(130, 16777215))
        self.agent_combox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.agent_combox.setModelColumn(0)
        self.agent_combox.setObjectName("agent_combox")
        self.agent_combox.addItem("")
        self.agent_combox.addItem("")
        self.agent_combox.addItem("")
        self.agent_combox.addItem("")
        self.agent_combox.addItem("")
        self.agent_combox.addItem("")
        self.gridLayout_2.addWidget(self.agent_combox, 0, 1, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.horizontalLayout_5.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(55, 16777215))
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setIndent(0)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.strtNum_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.strtNum_edit.sizePolicy().hasHeightForWidth())
        self.strtNum_edit.setSizePolicy(sizePolicy)
        self.strtNum_edit.setMaximumSize(QtCore.QSize(40, 16777215))
        self.strtNum_edit.setText("")
        self.strtNum_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.strtNum_edit.setPlaceholderText("")
        self.strtNum_edit.setClearButtonEnabled(False)
        self.strtNum_edit.setObjectName("strtNum_edit")
        self.horizontalLayout_5.addWidget(self.strtNum_edit)
        self.gridLayout_2.addLayout(self.horizontalLayout_5, 2, 2, 1, 1)
        self.address_lab = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.address_lab.sizePolicy().hasHeightForWidth())
        self.address_lab.setSizePolicy(sizePolicy)
        self.address_lab.setObjectName("address_lab")
        self.gridLayout_2.addWidget(self.address_lab, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.phone_lab = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_lab.sizePolicy().hasHeightForWidth())
        self.phone_lab.setSizePolicy(sizePolicy)
        self.phone_lab.setObjectName("phone_lab")
        self.gridLayout_2.addWidget(self.phone_lab, 1, 0, 1, 1)
        self.street_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.street_edit.sizePolicy().hasHeightForWidth())
        self.street_edit.setSizePolicy(sizePolicy)
        self.street_edit.setMaximumSize(QtCore.QSize(130, 16777215))
        self.street_edit.setText("")
        self.street_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.street_edit.setClearButtonEnabled(True)
        self.street_edit.setObjectName("street_edit")
        self.gridLayout_2.addWidget(self.street_edit, 2, 1, 1, 1)
        self.new_prop_head = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_prop_head.sizePolicy().hasHeightForWidth())
        self.new_prop_head.setSizePolicy(sizePolicy)
        self.new_prop_head.setObjectName("new_prop_head")
        self.gridLayout_2.addWidget(self.new_prop_head, 0, 0, 1, 1)
        self.type_combox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.type_combox.sizePolicy().hasHeightForWidth())
        self.type_combox.setSizePolicy(sizePolicy)
        self.type_combox.setMaximumSize(QtCore.QSize(130, 16777215))
        self.type_combox.setObjectName("type_combox")
        self.type_combox.addItem("")
        self.type_combox.addItem("")
        self.type_combox.addItem("")
        self.type_combox.addItem("")
        self.type_combox.addItem("")
        self.type_combox.addItem("")
        self.type_combox.addItem("")
        self.gridLayout_2.addWidget(self.type_combox, 3, 1, 1, 1)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSpacing(12)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.rooms_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rooms_edit.sizePolicy().hasHeightForWidth())
        self.rooms_edit.setSizePolicy(sizePolicy)
        self.rooms_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.rooms_edit.setObjectName("rooms_edit")
        self.horizontalLayout_6.addWidget(self.rooms_edit)
        self.floorNum_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.floorNum_edit.sizePolicy().hasHeightForWidth())
        self.floorNum_edit.setSizePolicy(sizePolicy)
        self.floorNum_edit.setMaximumSize(QtCore.QSize(70, 16777215))
        self.floorNum_edit.setObjectName("floorNum_edit")
        self.horizontalLayout_6.addWidget(self.floorNum_edit)
        self.gridLayout_2.addLayout(self.horizontalLayout_6, 3, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.price_lab = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price_lab.sizePolicy().hasHeightForWidth())
        self.price_lab.setSizePolicy(sizePolicy)
        self.price_lab.setObjectName("price_lab")
        self.horizontalLayout_3.addWidget(self.price_lab)
        self.price_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.price_edit.sizePolicy().hasHeightForWidth())
        self.price_edit.setSizePolicy(sizePolicy)
        self.price_edit.setMaximumSize(QtCore.QSize(85, 16777215))
        self.price_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.price_edit.setClearButtonEnabled(True)
        self.price_edit.setObjectName("price_edit")
        self.horizontalLayout_3.addWidget(self.price_edit)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 3, 4, 1, 1)
        self.owner_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.owner_edit.sizePolicy().hasHeightForWidth())
        self.owner_edit.setSizePolicy(sizePolicy)
        self.owner_edit.setMinimumSize(QtCore.QSize(0, 0))
        self.owner_edit.setMaximumSize(QtCore.QSize(130, 16777215))
        self.owner_edit.setSizeIncrement(QtCore.QSize(0, 0))
        self.owner_edit.setAutoFillBackground(True)
        self.owner_edit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.owner_edit.setInputMask("")
        self.owner_edit.setText("")
        self.owner_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.owner_edit.setClearButtonEnabled(True)
        self.owner_edit.setObjectName("owner_edit")
        self.gridLayout_2.addWidget(self.owner_edit, 1, 1, 1, 1)
        self.email_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.email_edit.sizePolicy().hasHeightForWidth())
        self.email_edit.setSizePolicy(sizePolicy)
        self.email_edit.setMaximumSize(QtCore.QSize(180, 16777215))
        self.email_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.email_edit.setClearButtonEnabled(True)
        self.email_edit.setObjectName("email_edit")
        self.gridLayout_2.addWidget(self.email_edit, 1, 3, 1, 1)
        self.phone_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.phone_edit.sizePolicy().hasHeightForWidth())
        self.phone_edit.setSizePolicy(sizePolicy)
        self.phone_edit.setMaximumSize(QtCore.QSize(119, 16777215))
        self.phone_edit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.phone_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.phone_edit.setClearButtonEnabled(True)
        self.phone_edit.setObjectName("phone_edit")
        self.gridLayout_2.addWidget(self.phone_edit, 1, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 4, 0, 1, 1)
        self.city_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.city_edit.sizePolicy().hasHeightForWidth())
        self.city_edit.setSizePolicy(sizePolicy)
        self.city_edit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.city_edit.setAutoFillBackground(False)
        self.city_edit.setText("")
        self.city_edit.setFrame(True)
        self.city_edit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.city_edit.setClearButtonEnabled(True)
        self.city_edit.setObjectName("city_edit")
        self.gridLayout_2.addWidget(self.city_edit, 2, 4, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lift_box = QtWidgets.QCheckBox(self.centralwidget)
        self.lift_box.setObjectName("lift_box")
        self.horizontalLayout.addWidget(self.lift_box)
        self.park_box = QtWidgets.QCheckBox(self.centralwidget)
        self.park_box.setObjectName("park_box")
        self.horizontalLayout.addWidget(self.park_box)
        self.shelter_box = QtWidgets.QCheckBox(self.centralwidget)
        self.shelter_box.setObjectName("shelter_box")
        self.horizontalLayout.addWidget(self.shelter_box)
        self.renew_box = QtWidgets.QCheckBox(self.centralwidget)
        self.renew_box.setObjectName("renew_box")
        self.horizontalLayout.addWidget(self.renew_box)
        self.equipped_box = QtWidgets.QCheckBox(self.centralwidget)
        self.equipped_box.setObjectName("equipped_box")
        self.horizontalLayout.addWidget(self.equipped_box)
        self.balcony_box = QtWidgets.QCheckBox(self.centralwidget)
        self.balcony_box.setObjectName("balcony_box")
        self.horizontalLayout.addWidget(self.balcony_box)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 1, 1, 3)
        self.area_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.area_edit.sizePolicy().hasHeightForWidth())
        self.area_edit.setSizePolicy(sizePolicy)
        self.area_edit.setMaximumSize(QtCore.QSize(50, 16777215))
        self.area_edit.setObjectName("area_edit")
        self.gridLayout_2.addWidget(self.area_edit, 3, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 9, 0, 1, 5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.update_but = QtWidgets.QPushButton(self.centralwidget)
        self.update_but.setObjectName("update_but")
        self.horizontalLayout_2.addWidget(self.update_but)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 7, 4, 1, 1)
        self.search_lab = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_lab.sizePolicy().hasHeightForWidth())
        self.search_lab.setSizePolicy(sizePolicy)
        self.search_lab.setMaximumSize(QtCore.QSize(130, 16777215))
        self.search_lab.setObjectName("search_lab")
        self.gridLayout_2.addWidget(self.search_lab, 7, 0, 1, 1)
        self.search_edit = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_edit.sizePolicy().hasHeightForWidth())
        self.search_edit.setSizePolicy(sizePolicy)
        self.search_edit.setMaximumSize(QtCore.QSize(300, 16777215))
        self.search_edit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.search_edit.setObjectName("search_edit")
        self.gridLayout_2.addWidget(self.search_edit, 7, 1, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.search_but = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_but.sizePolicy().hasHeightForWidth())
        self.search_but.setSizePolicy(sizePolicy)
        self.search_but.setMaximumSize(QtCore.QSize(50, 16777215))
        self.search_but.setObjectName("search_but")
        self.horizontalLayout_4.addWidget(self.search_but)
        self.clear_res_but = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_res_but.sizePolicy().hasHeightForWidth())
        self.clear_res_but.setSizePolicy(sizePolicy)
        self.clear_res_but.setMaximumSize(QtCore.QSize(50, 16777215))
        self.clear_res_but.setObjectName("clear_res_but")
        self.horizontalLayout_4.addWidget(self.clear_res_but)
        self.gridLayout_2.addLayout(self.horizontalLayout_4, 7, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 758, 22))
        self.menuBar.setObjectName("menuBar")
        self.help_menu = QtWidgets.QMenu(self.menuBar)
        self.help_menu.setObjectName("help_menu")
        self.file_menu = QtWidgets.QMenu(self.menuBar)
        self.file_menu.setObjectName("file_menu")
        MainWindow.setMenuBar(self.menuBar)
        self.howtouse = QtWidgets.QAction(MainWindow)
        self.howtouse.setObjectName("howtouse")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.openXL = QtWidgets.QAction(MainWindow)
        self.openXL.setObjectName("openXL")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.help_menu.addAction(self.howtouse)
        self.help_menu.addAction(self.about)
        self.file_menu.addAction(self.openXL)
        self.file_menu.addAction(self.exit)
        self.menuBar.addAction(self.file_menu.menuAction())
        self.menuBar.addAction(self.help_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.agent_combox, self.owner_edit)
        MainWindow.setTabOrder(self.owner_edit, self.phone_edit)
        MainWindow.setTabOrder(self.phone_edit, self.email_edit)
        MainWindow.setTabOrder(self.email_edit, self.street_edit)
        MainWindow.setTabOrder(self.street_edit, self.strtNum_edit)
        MainWindow.setTabOrder(self.strtNum_edit, self.neighborhood_edit)
        MainWindow.setTabOrder(self.neighborhood_edit, self.city_edit)
        MainWindow.setTabOrder(self.city_edit, self.type_combox)
        MainWindow.setTabOrder(self.type_combox, self.area_edit)
        MainWindow.setTabOrder(self.area_edit, self.rooms_edit)
        MainWindow.setTabOrder(self.rooms_edit, self.floorNum_edit)
        MainWindow.setTabOrder(self.floorNum_edit, self.price_edit)
        MainWindow.setTabOrder(self.price_edit, self.lift_box)
        MainWindow.setTabOrder(self.lift_box, self.park_box)
        MainWindow.setTabOrder(self.park_box, self.shelter_box)
        MainWindow.setTabOrder(self.shelter_box, self.renew_box)
        MainWindow.setTabOrder(self.renew_box, self.equipped_box)
        MainWindow.setTabOrder(self.equipped_box, self.balcony_box)
        MainWindow.setTabOrder(self.balcony_box, self.comments_edit)
        MainWindow.setTabOrder(self.comments_edit, self.excel_but)
        MainWindow.setTabOrder(self.excel_but, self.search_edit)
        MainWindow.setTabOrder(self.search_edit, self.search_but)
        MainWindow.setTabOrder(self.search_but, self.clear_res_but)
        MainWindow.setTabOrder(self.clear_res_but, self.update_but)
        MainWindow.setTabOrder(self.update_but, self.result_table)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.excel_but.setText(_translate("MainWindow", "הכנס לאקסל"))
        self.result_table.setSortingEnabled(True)
        item = self.result_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "תאריך"))
        item = self.result_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "סטטוס"))
        item = self.result_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "סוכן"))
        item = self.result_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "בעל הנכס"))
        item = self.result_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "יישוב"))
        item = self.result_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "שכונה"))
        item = self.result_table.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "כתובת"))
        item = self.result_table.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "סוג נכס"))
        item = self.result_table.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "חדרים"))
        item = self.result_table.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "קומה"))
        item = self.result_table.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "מ\"ר"))
        item = self.result_table.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "תוספות"))
        item = self.result_table.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "מחיר"))
        item = self.result_table.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "מס\' טלפון"))
        item = self.result_table.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "דוא\"ל"))
        item = self.result_table.horizontalHeaderItem(15)
        item.setText(_translate("MainWindow", "הערות"))
        self.label_3.setText(_translate("MainWindow", "הערות"))
        self.neighborhood_edit.setPlaceholderText(_translate("MainWindow", "שכונה"))
        self.agent_combox.setItemText(0, _translate("MainWindow", "בחר שם סוכן"))
        self.agent_combox.setItemText(1, _translate("MainWindow", "שמואל"))
        self.agent_combox.setItemText(2, _translate("MainWindow", "אופק"))
        self.agent_combox.setItemText(3, _translate("MainWindow", "אור"))
        self.agent_combox.setItemText(4, _translate("MainWindow", "קטיה"))
        self.agent_combox.setItemText(5, _translate("MainWindow", "טום"))
        self.label_4.setText(_translate("MainWindow", "בניין/דירה:"))
        self.address_lab.setText(_translate("MainWindow", "כתובת:"))
        self.label_2.setText(_translate("MainWindow", "פרטים:"))
        self.phone_lab.setText(_translate("MainWindow", "דרכי תקשורת:"))
        self.street_edit.setPlaceholderText(_translate("MainWindow", "רחוב"))
        self.new_prop_head.setText(_translate("MainWindow", "הכנס נכס חדש:"))
        self.type_combox.setItemText(0, _translate("MainWindow", "סוג נכס"))
        self.type_combox.setItemText(1, _translate("MainWindow", "דירה"))
        self.type_combox.setItemText(2, _translate("MainWindow", "קוטג\'"))
        self.type_combox.setItemText(3, _translate("MainWindow", "פנטהאוז"))
        self.type_combox.setItemText(4, _translate("MainWindow", "דירת גן"))
        self.type_combox.setItemText(5, _translate("MainWindow", "דירת גג"))
        self.type_combox.setItemText(6, _translate("MainWindow", "דופלקס"))
        self.rooms_edit.setPlaceholderText(_translate("MainWindow", "חדרים"))
        self.floorNum_edit.setPlaceholderText(_translate("MainWindow", "קומה / מתוך"))
        self.price_lab.setText(_translate("MainWindow", "מחיר: "))
        self.owner_edit.setPlaceholderText(_translate("MainWindow", "בעל הנכס"))
        self.email_edit.setPlaceholderText(_translate("MainWindow", "דוא\"ל"))
        self.phone_edit.setPlaceholderText(_translate("MainWindow", "טלפון"))
        self.label.setText(_translate("MainWindow", "תוספות:"))
        self.city_edit.setPlaceholderText(_translate("MainWindow", "עיר"))
        self.lift_box.setText(_translate("MainWindow", "מעלית"))
        self.park_box.setText(_translate("MainWindow", "חניה"))
        self.shelter_box.setText(_translate("MainWindow", "ממ\"ד"))
        self.renew_box.setText(_translate("MainWindow", "משופצת"))
        self.equipped_box.setText(_translate("MainWindow", "מרוהטת"))
        self.balcony_box.setText(_translate("MainWindow", "מרפסת"))
        self.area_edit.setPlaceholderText(_translate("MainWindow", "מ\"ר"))
        self.update_but.setText(_translate("MainWindow", "עדכן"))
        self.search_lab.setText(_translate("MainWindow", "חפש נכס:"))
        self.search_but.setText(_translate("MainWindow", "חפש"))
        self.clear_res_but.setText(_translate("MainWindow", "אפס"))
        self.help_menu.setTitle(_translate("MainWindow", "עזרה"))
        self.file_menu.setTitle(_translate("MainWindow", "קובץ"))
        self.howtouse.setText(_translate("MainWindow", "הסבר שימוש"))
        self.about.setText(_translate("MainWindow", "אודות"))
        self.openXL.setText(_translate("MainWindow", "פתח קובץ נכסים"))
        self.exit.setText(_translate("MainWindow", "יציאה"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

